name: React + Node CD

on:
  push:
    branches:
      - main # Only deploy from main branch

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Deploy React frontend to GitHub Pages
      - name: Deploy frontend to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
